services:
  backend:
    build:
      context: ./app_backend
      dockerfile: Dockerfile
    container_name: policy-chatbot-backend
    ports:
      - "8000:8000"
    env_file:
      - ./app_backend/.env
    volumes:
      - chroma_data:/service/app_backend/chroma_db
    restart: unless-stopped

  frontend:
    build:
      context: ./app-frontend
      dockerfile: Dockerfile
    container_name: policy-chatbot-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  chroma_data:
